apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-from-repo
  title: Crear app desde repo base con CI
  description: Clona repo base, crea nuevo repo y añade CI

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Configuración
      required:
        - appName
        - repoName
        - baseRepo
      properties:
        appName:
          type: string
          title: Nombre de la aplicación

        repoName:
          type: string
          title: Nombre del nuevo repositorio

        baseRepo:
          type: string
          title: Repositorio base
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    # 1. CLONAR REPO BASE
    - id: fetch-base
      name: Clonar repo base
      action: fetch:template
      input:
        url: ${{ parameters.baseRepo }}
        values:
          name: ${{ parameters.appName }}

    # 2. AÑADIR TU CI
    - id: add-ci
      name: Añadir pipeline CI
      action: fetch:template
      input:
        url: ./ci-template
        targetPath: .github/workflows

    # 3. CREAR REPO NUEVO
    - id: publish
      name: Crear repo en GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=hdteck&repo=${{ parameters.repoName }}
        defaultBranch: main

    # 4. REGISTRAR EN BACKSTAGE
    - id: register
      name: Registrar en catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
